name: Android Debug CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Project
      run: ./gradlew buildFreeDebug

    - name: Bundle Debug AAB
      run: ./gradlew bundleFreeDebug

    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: app--free-debug
        path: app/build/outputs/bundle/freeDebug
        #path: app/build/outputs/apk/free/debug/app-free-ebug.apk
        
    #- name: Create Github release
    #  uses: softprops/action-gh-release@v1
     # with:
    #    name: ${{ github.event.inputs.versionName }}
   #     tag_name:  ${{ github.event.inputs.versionNumber }}

        
